# -*- coding: utf-8 -*-
"""Final Project Architektur

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwwPiaROGBxXWO5a7q3S5zLOV-jlg7gH
"""

import sys
sys.path.append('./')
from mylibs import *

class TestModel(tf.keras.Model):

  def __init__(self, num_units, num_layers, num_heads, num_conv_layers):

    super(TestModel, self).__init__()
    
    
    self.conv_block = []
    
    for i in range(num_conv_layers):
        
        self.conv_block.append(tf.keras.layers.Conv1D(8*i + 8, 3, activation='relu'))

        
    self.dense_layers =[]
    
    for i in range(num_layers):
            self.dense_layers.append(tf.keras.layers.Dense(num_units, activation='relu'))
    
    self.mha = tf.keras.layers.MultiHeadAttention(num_heads, 640)
    self.dropout = tf.keras.layers.Dropout(0.3)
    self.dense = tf.keras.layers.Dense(640, activation = "sigmoid")
    self.dense2 = tf.keras.layers.Dense(640, activation = "sigmoid")
    

  def call(self, x):
    
    for layer in self.conv_block:
        x = layer(x)
                
    x = self.mha(x, x)
    x = self.dropout(x)
    
    for layer in self.dense_layers:
        x = layer(x)
        
    output_eye = self.dense(x)
    output_muscle = self.dense2(x)

    output_eye = tf.math.reduce_mean(output_eye, axis=1)
    output_muscle = tf.math.reduce_mean(output_muscle, axis=1)

    return output_eye, output_muscle